spring.application.name=trust_net
# Server
server.port=8080
spring.security.user.password=disabled
spring.security.user.name=disabled

# MongoDB Atlas
spring.data.mongodb.uri=mongodb+srv://Anshul:Anshul1234@shoppingcart.bufa1em.mongodb.net/ngoconnect?retryWrites=true&w=majority&appName=shoppingcart

#logging.level.org.mongodb.driver=DEBUG



# JWT
app.jwt.secret=your_super_secret_key_minimum_32_characters_long
app.jwt.expiration-ms=86400000

# Cloudinary
cloudinary.cloud-name=df5dzu5xf
cloudinary.api-key=648228643675767
cloudinary.api-secret=pOKT2oQEX45vsW645CJaezDziVs

# Razorpay
razorpay.key-id=rzp_test_SZ6DCpKntuMM5f
razorpay.key-secret=PbiBPFX4iO1V7RI89PZjYT6N

spring.data.mongodb.auto-index-creation=true